# Generated by Django 4.2.26 on 2025-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_ap_user_f93cf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_ap_directi_2c4fbe_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], default='sent', max_length=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
