# Generated by Django 4.2.26 on 2025-11-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('A', 'Usuário A'), ('B', 'Usuário B')], max_length=1)),
                ('text', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('sent', 'sent'), ('received', 'received')], default='sent', max_length=10)),
                ('viewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user'], name='messages_ap_user_5902d1_idx'), models.Index(fields=['created_at'], name='messages_ap_created_78ae4c_idx')],
            },
        ),
    ]
