# Generated by Django 4.2.26 on 2025-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_ap_user_5902d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_ap_created_78ae4c_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'created_at'], name='messages_ap_user_f93cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction'], name='messages_ap_directi_2c4fbe_idx'),
        ),
    ]
